story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story1/', views.index, name='index'),
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='homeku'),
    path('about/',views.about,name = 'about'),
    path('experiences/',views.experiences, name = 'experiences'),
    path('abilities/',views.abilities,name = 'abilities'),
    path('hobby/',views.hobby,name = 'Hobby'),
    # path('story1',views.tes,name = 'tes'),
    
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('result/', views.jadwal_ku,name = 'liat_jadwal'),
    path('<int:pk>/', views.delete, name = 'hapus'),
    path('<int:pk>', views.detail, name='detail'),
    # path('tes/', views.tes, name = 'tes'),
    
]

webpli/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('', include('story4.urls')),
    path('story5/', include('story5.urls')),
]

story1/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_mata_kuliah = models.CharField(blank=False, max_length = 100)
    nama_dosen = models.CharField(blank=False, max_length=100)
    jumlah_sks = models.CharField(blank=False, max_length = 3)
    deskripsi_mata_kuliah = models.CharField(blank=False, max_length = 200)
    tahun_semester = models.CharField(blank=False, max_length = 50)
    ruang_kelas = models.CharField(blank=False, max_length = 100)
    

story5/forms.py
from django import forms

class formulir(forms.Form):
    nama_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    nama_dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True
    }))
    deskripsi_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    tahun_semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester Tahun',
        'type' : 'text',
        'required' : True
    }))
    ruang_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Lokasi Ruang Kelas',
        'type' : 'text',
        'required' : True
    }))

story1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story1/tes.html')

story4/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'story4/homeku.html')

def about(request):
    return render(request, 'story4/about.html')

def experiences(request):
    return render(request, 'story4/experiences.html')

def abilities(request):
    return render(request, 'story4/abilities.html')

def hobby(request):
    return render(request, 'story4/Hobby.html')

def tes(request):
    return render(request, 'story1/tes.html')

# def hapus(request):
#     return render(request, 'story5/index.html')

story5/views.py
from django.shortcuts import render, redirect,HttpResponse,get_object_or_404
from . import forms,models
from .forms import formulir
from .models import Jadwal

# Create your views here.
def jadwal_ku(request):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if (context.is_valid()):
            context1 = models.Jadwal()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("story5:liat_jadwal")
    else:
        context = forms.formulir()
        context1 = models.Jadwal.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal_ku' : context1
        }
    return render(request, 'story5/index.html', context_dictio)
    

def delete(request, pk):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if(context.is_valid()):
            context1 = models.Jadwal()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("story5:liat_jadwal")
    else:
        models.Jadwal.objects.filter(pk = pk).delete()
        context = forms.formulir()
        context1 = models.Jadwal.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal_ku' : context1
        }
        return render(request, 'story5/index.html', context_dictio)
    
def detail(request, pk):
    matkul = get_object_or_404(Jadwal, id=pk)
    return render(request, 'story5/detail.html', {'post': matkul})

story1/templates/story1/tes.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Bismillah</title>
    <link rel="stylesheet" href="{% static 'story1/coba.css' %}">
</head>  
<body>
  
      <div id="header">
        <h1> Welcome to My Website</h1>
      </div>
<div id = "profile">
    <img src="{% static 'story1/images/mukaku.jpg' %}" alt="" width="150" height="auto" >
</div>
<div id = "main">
<table style="width: auto;">
  <tr>
    <td>Nama</td>
    <td>Muhammad Rafli Amardito</td> 
  </tr>
  <tr>
    <td>NPM</td>
    <td>1906307523</td>
  
  </tr>
  <tr>
    <td>Angkatan</td>
    <td><a href="https://maung.id/muhammad.rafli91" target="_blank"> <i>MAUNG 2019</i></a></td></td>
   
  </tr>
  <tr>
    <td>Student of</td>
    <td>Fasilkom Universitas Indonesia </td>     
  </tr>
  <tr>
      <td>Hobi</td>
      <td>Bermain game Fifa</td>
  </tr>
</table>

<h2> Deskripsi Diri</h2>
<h4> Saya lahir di Jakarta pada tanggal 12 Agustus 2001. Saya adalah anak kedua dari dua bersaudara. Sejak SMA saya ingin sekali bisa masuk di Universitas Indonesia. Saya adalah fans berat dari klub sepakbola FC Barcelona. Oleh karena itu warna background Website saya campuran antara warna merah dan biru. Saya masih pemula dalam hal membuat dan merancang web.</h4>

    <h2>Riwayat Pendidikan</h2>
    
    <table>
      <tr>
        <th>Jenjang Pendidikan</th>
        <th>Tahun</th> 
      </tr>
      <tr>
        <td>Universitas Indonesia</td>
        <td>2019-sekarang</td>
      
      </tr>
      <tr>
        <td>SMAN 54 Jakarta</td>
        <td>2016-2019</td>
       
      </tr>
      <tr>
        <td>SMPN 52 Jakarta</td>
        <td>2013 - 2016</td>     
      </tr>
      <tr>
          <td>SDN CC 02</td>
          <td>2007-2013</td>
      </tr>
    </table>
  </style>
  </div>
    <div id="socmed">
      <h2>Social Media</h2>
      <a href="https://www.instagram.com/rafliamardito/" target="_blank">
        <img class="sospli" src="{% static 'story1/images/instagram.png' %}" alt="" alt="Ig @rafliamardito" width="50" height="50" hspace="20"/>
      </a>
      <a href="https://www.facebook.com/muhammadrafli.amardito" target="_blank">
        <img class="sospli" src="{% static 'story1/images/facebook.png' %}" alt="" width="50" height="50" hspace="20"/>
      </a>
      <a href="https://www.linkedin.com/in/rafli-amardito-2533bb192/" target="_blank">
        <img class="sospli" src="{% static 'story1/images/linkedin.png' %}" alt="" width="50" height="50" hspace="20"/>
      </a>
  </div>

  <div id="footer">
      Copyright &copy; 2020 M. Rafli Amardito.
  </div>
  </body>
  
</html>

story4/templates/story4/Hobby.html
{% extends 'base.html'%} {% load static %} {% block content %}
<head>
    
    <link rel="stylesheet" href="{% static 'story4/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'story4/fix.css' %}">
</head>    
        <div id="classes" class="layout_padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text_align_center">
                        <h2 class="heading_section" style="margin-bottom: 65px;">Hobby</h3>
                    </div>
                </div>
                <div class="row">
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/jordan.jpg' %}" alt="" width="246" height="246">
                            <h4>Basketball</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/fifa.jpg' %}" alt="" width="246" height="246">
                            <h4>Fifa</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/futsal.jpg' %}" alt="" width="246" height="246">
                            <h4>Futsal</h4>
                        </div>
                    </div>
                    <div id="classes" class="layout_padding">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12 text_align_center">
                                    <h2 class="heading_section" style="margin-bottom: 65px;">Interest</h3>
                                </div>
                            </div>
                            <div class="row">
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/bisnis.jpg' %}" alt="#" />
                            <h4>Business</h4>
                        </div>
                    </div>
    
                    <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/teknologi.png' %}" alt="#" />
                            <h4>Technology</h4>
                        </div>
                    </div>
    
                     <div class="col-md-4">
                        <div class="full dance_form_name">
                            <img src="{% static 'story4/images/entre.jpg' %}" alt="#" />
                            <h4>Entrepreneur</h4>
                        </div>
                    </div>
    
                </div>
            </div>
        </div>

{% endblock %}

story4/templates/story4/abilities.html
{% extends 'base.html'%} {% load static %} {% block content %}  
   
<section id="skill">
    <div class="skill container">
        <div class="skill-top">
            <h1 class="section-title">SKILLS</h1>
        </div>
        <div class="skill-bottom">
            <div class="skill-item">
                <h1>Leadership</h1>
                <div class="icon"><img src="{% static 'story4/images/star-leadership.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Public Speaking</h1>
                <div class="icon"><img src="{% static 'story4/images/star-public-speak.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Python</h1>
                <div class="icon"><img src="{% static 'story4/images/star-python.png' %}" /></div>
            </div>
            <div class="skill-item">
                <h1>Team Management</h1>
                <div class="icon"><img src="{% static 'story4/images/star-team-manage.png' %}" /></div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

story4/templates/story4/about.html
{% extends 'base.html'%} {% load static %} {% block content %}  
   
<div class="background-white">
    <div id="profile" class="container">
        <h2>Profile</h2>
        <p class="lead">I'm a creative webdeveloper</p>

        <hr>
        <div id = "profile">
        <img id="mukaku" src="{% static 'story4/images/mukaku.jpg' %}"alt="" width="246" height="246" style="margin: auto;">
        </div>

        <div class="row">
            <div class="col-md-4">
                <h3>About me</h3>
                <p>
                    im a student of University of Indonesia. I love to playing video games  , futsal, and also basketball, i like about business stuff. </p>
            </div>
            <div class="col-md-4">
                <h3>Details</h3>
                <p>
                    <strong>Name:</strong><br> Muhammad Rafli Amardito<br>
                    <strong>Age:</strong><br> 19 years<br>
                    <strong>Location:</strong><br> Jakarta, Indonesia, Earth <br>
                    <strong>NPM:</strong><br> 1906307523
                </p>
            </div>
        </div>
    </div>
{% endblock %}

story4/templates/story4/experiences.html
{% extends 'base.html'%} {% load static %} {% block content %}  

        <div class="row">
            <div class="column">
                <h3 data-aos="fade-up">Education</h3>
            </div>
        </div>
        

        <div class="row block-large-1-2 block-900-full work-positions">

            <div class="column" data-aos="fade-up">
                <div class="position">
                    <div class="position__header">
                        <h6>
                            <span class="position__co">University of Indonesia</span>
                        </h6>
                        <div class="position__timeframe">
                             2019 - present
                        </div>
                    </div>

                </div>
            </div>
            <div class="row block-large-1-2 block-900-full work-positions">

                <div class="column" data-aos="fade-up">
                    <div class="position">
                        <div class="position__header">
                            <h6>
                                <span class="position__co">54 Senior High School</span>
                            </h6>
                            <div class="position__timeframe">
                                 2016-2019
                            </div>
                        </div>
    
                    </div>
                </div>
                <div class="row block-large-1-2 block-900-full work-positions">

                    <div class="column" data-aos="fade-up">
                        <div class="position">
                            <div class="position__header">
                                <h6>
                                    <span class="position__co">54 junior High School</span>
                                </h6>
                                <div class="position__timeframe">
                                     2013-2016
                                </div>
                            </div>
        
                        </div>
                    </div>
                    <div class="row block-large-1-2 block-900-full work-positions">

                        <div class="column" data-aos="fade-up">
                            <div class="position">
                                <div class="position__header">
                                    <h6>
                                        <span class="position__co">02 Elementary School</span>
                                    </h6>
                                    <div class="position__timeframe">
                                         2007-2013
                                    </div>
                                </div>
            
                            </div>
                        </div>
            
        </div>

        <div class="row">
            <div class="column">
                <h3 data-aos="fade-up">Personal experiences</h3>
            </div>
        </div>
        <div class="row block-large-1-2 block-900-full work-positions">

            <div class="column" data-aos="fade-up">
                <div class="position">
                    <div class="position__header">
                        <h6>
                            <span class="position__co">Person in charge Liaison Officer of Open House Fasilkom UI 2020</span>
                        </h6>
                        <div class="position__timeframe">
                             June 2020-present
                        </div>
                    </div>

                </div>
            </div>
            <div class="row block-large-1-2 block-900-full work-positions">

                <div class="column" data-aos="fade-up">
                    <div class="position">
                        <div class="position__header">
                            <h6>
                                <span class="position__co">Staff Public Relation of Executive Council of Student CS UI</span>
                            </h6>
                            <div class="position__timeframe">
                                 Februari 2020- Present
                            </div>
                        </div>
    
                    </div>
                </div>
                <div class="row block-large-1-2 block-900-full work-positions">

                    <div class="column" data-aos="fade-up">
                        <div class="position">
                            <div class="position__header">
                                <h6>
                                    <span class="position__co">Staff food & beverages of COMPFEST XII</span>
                                </h6>
                                <div class="position__timeframe">
                                     2020
                                </div>
                            </div>
        
                        </div>
                    </div>
                    <div class="row block-large-1-2 block-900-full work-positions">

                        <div class="column" data-aos="fade-up">
                            <div class="position">
                                <div class="position__header">
                                    <h6>
                                        <span class="position__co">Staff Games of PERAK 2020</span>
                                    </h6>
                                    <div class="position__timeframe">
                                         2020
                                    </div>
                                </div>
            
                            </div>
                        </div>
                        <div class="row block-large-1-2 block-900-full work-positions">

                            <div class="column" data-aos="fade-up">
                                <div class="position">
                                    <div class="position__header">
                                        <h6>
                                            <span class="position__co">Staff equipment of Fasilkom’s graduation 2020</span>
                                        </h6>
                                        <div class="position__timeframe">
                                             2020
                                        </div>
                                    </div>
                
                                </div>
                            </div>
        
{% endblock %}

story4/templates/story4/homeku.html
{% extends 'base.html'%} {% load static %} {% block content %}    
    <div class="row hero-content">

        <div class="column large-full">

            <h1>
            Hello, I'm Rafli, <br>
            a creative web developer <br>
            & designer currently <br>
            based somewhere.
            </h1>

        </div> 

    </div>
    <br>

    <div id="socmed">
        <h2>Find me on</h2>
        <a href="https://www.instagram.com/rafliamardito/" target="_blank">
          <img class="sospli" src="{% static 'story4/images/instagram.png' %}" alt="" alt="Ig @rafliamardito" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.facebook.com/muhammadrafli.amardito" target="_blank">
          <img class="sospli" src="{% static 'story4/images/facebook.png' %}" alt="" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.linkedin.com/in/rafli-amardito-2533bb192/" target="_blank">
          <img class="sospli" src="{% static 'story4/images/linkedin.png' %}" alt="" width="50" height="50" hspace="20"/>
        </a>
    </div>
{% endblock %}

story5/templates/story5/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>

    <title>Jadwal</title>
  </head>
  <style>
    body {
    background-color: #141E30;
    color: aliceblue;
    }
    .table {
        color:antiquewhite !important;
    }
    </style>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"><h3>Jadwal-Rapli</h1></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link ml-3" href="{% url 'story4:homeku' %}">Story 4</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
<div class="container my-4">
    <div class="jumbotron" style="background-color: #141E30;">
        <h1 class="display-4">{{ post.nama_mata_kuliah }}</h1>
        <p class="lead">{{ post.tahun_semester }}</p>
        <p>{{ post.deskripsi_mata_kuliah }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-3">Dosen : <span class="badge badge-dark">{{ post.nama_dosen }}</span></h4>
            <h4 class="col-10 col-md-3">Jumlah SKS : <span class="badge badge-dark">{{ post.jumlah_sks }} SKS</span></h4>
            <h4 class="col-10 col-md-5">Ruang : <span class="badge badge-dark">{{ post.ruang_kelas }}</span></h4>
        </div>
        <a class="btn btn-outline-light mt-4" href="{% url 'story5:liat_jadwal' %}" role="button">BACK</a>
    </div>
</div>


</div>
  </body>
</html>

story5/templates/story5/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>

    <title>Jadwal</title>
  </head>
  <style>
    body {
    background-color: #141E30;
    color: aliceblue;
    }
    .table {
        color:antiquewhite !important;
    }
    </style>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"><h3>Jadwal-Rapli</h1></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link ml-3" href="{% url 'story4:homeku' %}">Story 4</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
<section class="inputJadwal" id="inputJadwal">
    <div class="container pt-5 pb-3 justify-content">
        <div class="row pt-5">
            <div class="col-md-4">
                <div class="card text-white bg-primary mb-3 pb-3 text-center" style="max-width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title"><h2><b>Isi Jadwal</b></h2></h5>
                      <p class="card-text"><i>Pengisian jadwal hanya dilakukan oleh mahasiswa Fakultas Ilmu Komputer Universitas Indonesia.</i></p>
                    </div>
                </div>
              
            </div>
            <div class="col-md-6">
                <form action="" method="POST" class="ml-5">
                    {% csrf_token %}
                    {{ formulir }}
                    <div class = "centre-items" style = "margin-top: 2%; color:azure">
                        <input type = "submit" class="btn btn-primary" value="Submit"> 
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="cekjadwal" id="cekjadwal">
    <div class="table-responsive" id="Table">
        <table class="table table-hover">
            <thead>
                
                <tr>
                    <th scope="col">Nama Mata Kuliah</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            {% for i in jadwal_ku %}
            <tbody>
                <tr>
                    <td>{{i.nama_mata_kuliah}}</td>
                    <td>
                        <a href="{% url 'story5:detail' i.id %}" class="btn btn-primary" style="background-color: silver;border-color: silver;">Details</a>
                    <a  href = "{% url 'story5:hapus' pk=i.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>
                </button></a>
                </td>
                </tr>
            </tbody>
            
            {% endfor %}
        </table>
        

    
</section>

<footer class="bg-dark">
    <div class="container mt-3">
        <div class="row pt-1">
            <div class="col text-center text-white">
                <i>Copyright 2020.</i>
            </div>
        </div>
    </div>
</footer>
    
  </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>HOME-STORY 3</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'story4/fix.css' %}">
    
</head>

<body id="top">

    <div id="header-content">
    
        <nav class="row header-nav-wrap">
            <ul class="header-nav">
                <li><a class="smoothscroll"  href="{% url 'story4:homeku' %}" title="">Home</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:about' %}" title="">Profile</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:experiences' %}" title="">Experiences</a></li>
                <li><a class="smoothscroll"  href="{% url 'story4:abilities' %}" title="">Abilities</a></li>
                <li><a href="{% url 'story4:Hobby' %}" title="">Hobby&Interest</a></li>
                <li><a href="{% url 'story1:index' %}" title="">My Another Website</a></li>
                <li><a href="https://story6-pli.herokuapp.com/" title="">Activity</a> 
                <a href="{% url 'story5:liat_jadwal' %}">JadwalKu</a  
            </ul>
        </nav>
    </div>
    {% block content %} {% endblock %}
    <div id="footer">
        Copyright &copy; 2020 M. Rafli Amardito.
    </div>
</body>

</html>